apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 7368
      targetPort: 7368
  type: ClusterIP