spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: e-sales
    password: e-sales
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 7368
