spring:
  data:
    mongodb:
      username: admin
      password: admin
      hosts: localhost
      port: 27017
      database: utilisateurs
      authentication-database: admin

server:
  port: 8090
