spring:
  data:
    mongodb:
      username: e-sales
      password: e-sales
      hosts: localhost
      port: 27017
      database: utilisateurs
      authentication-database: admin

server:
  port: 8090
