apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: mohamedtergui/config-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
      volumes:
        - name: config-repo
          configMap:
            name: config-repo  # ConfigMap containing the configuration files