apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8222  # Port exposed by the Service
      targetPort: 8222  # Port exposed by the container
      nodePort: 30000  # Optional: Specify a NodePort (default range: 30000-32767)
  type: NodePort  # Expose the API Gateway externally