server:
  port: 8082

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: order-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}