server:
  port: 8083

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:mysql://localhost:3306/esales_orders
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}