apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 8761  # Port exposed by the Eureka Server
      targetPort: 8761  # Port exposed by the container
  type: ClusterIP